import { Injectable, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { tap } from 'rxjs/operators';

@Injectable({
  providedIn: 'root',
})
export class Productservice {
  private products = signal([
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'men',
      createdAt: '2026-02-21T20:43:00.206568',
      description: 'ក្រណាត់: Cotton 100%, ទំហំ: S-XXL, ពណ៌: ខ្មៅ/សស/ខៀវ, សម្រាប់ប្រុស។',
      id: 1,
      image: ['/images/fashion/clothing/men/7.png'],
      name: 'អាវយឺតប្រុស Cotton',
      price: 30,
      specs: 'ក្រណាត់: Cotton 100%, ទំហំ: S-XXL, ពណ៌: ខ្មៅ/សស/ខៀវ, សម្រាប់ប្រុស។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'men',
      createdAt: '2026-02-21T20:45:17.951379',
      description: 'សម្ភារៈ: Leather សិប្បនិម្មិត, ទំហំ: 38-45, ពណ៌: ខ្មៅ/ត្នោត, ស្រាល និងរឹងមាំ។',
      id: 2,
      image: ['/images/fashion/shoes/9.png'],
      name: 'ស្បែកជើង Loafer បុរស',
      price: 20,
      specs: 'សម្ភារៈ: Leather សិប្បនិម្មិត, ទំហំ: 38-45, ពណ៌: ខ្មៅ/ត្នោត, ស្រាល និងរឹងមាំ។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'men',
      createdAt: '2026-02-21T20:45:47.126144',
      description: 'នាឡិកាឌីជីថល, អាងទឹក: 50m, ក្រុម: Casio, ខ្សែ: Resin, ថ្ម: Solar។',
      id: 3,
      image: ['/images/fashion/watches/men/6.png'],
      name: 'នាឡិកា Casio Solar',
      price: 100,
      specs: 'នាឡិកាឌីជីថល, អាងទឹក: 50m, ក្រុម: Casio, ខ្សែ: Resin, ថ្ម: Solar។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'men',
      createdAt: '2026-02-21T20:46:24.877083',
      description: 'ក្រណាត់: Denim 98% Cotton, ទំហំ: 28-38, កាត់: Slim Fit, ពណ៌: ខៀវចាស់។',
      id: 4,
      image: ['/images/fashion/clothing/men/6.png'],
      name: 'ខោ Jeans Slim Fit',
      price: 80,
      specs: 'ក្រណាត់: Denim 98% Cotton, ទំហំ: 28-38, កាត់: Slim Fit, ពណ៌: ខៀវចាស់។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'men',
      createdAt: '2026-02-21T20:46:57.933157',
      description: 'នាឡិកា Analog, ក្រឡុក: Stainless Steel, ក្រឡុកកញ្ចក់: Mineral, អាងទឹក: 30m។',
      id: 5,
      image: ['/images/fashion/watches/men/9.png'],
      name: 'នាឡិកា Analog Stainless Steel',
      price: 60,
      specs: 'នាឡិកា Analog, ក្រឡុក: Stainless Steel, ក្រឡុកកញ្ចក់: Mineral, អាងទឹក: 30m។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'men',
      createdAt: '2026-02-21T20:47:28.659479',
      description: 'ក្រណាត់: Polyester, ទំហំ: S-XL, មានក្បាលភ្ជាប់, សម្រាប់រដូវវស្សា។',
      id: 6,
      image: ['/images/fashion/clothing/men/9.png'],
      name: 'អាវ Hoodie មានក្បាល',
      price: 30,
      specs: 'ក្រណាត់: Polyester, ទំហំ: S-XL, មានក្បាលភ្ជាប់, សម្រាប់រដូវវស្សា។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'women',
      createdAt: '2026-02-21T20:47:54.710747',
      description: 'ក្រណាត់: Linen 100%, ទំហំ: S-XXL, ពណ៌: សស/ខៀវ/បៃតង, ត្រជាក់ស្រស់។',
      id: 7,
      image: ['/images/fashion/clothing/women/13.png'],
      name: 'អាវ Linen ស្រី',
      price: 40,
      specs: 'ក្រណាត់: Linen 100%, ទំហំ: S-XXL, ពណ៌: សស/ខៀវ/បៃតង, ត្រជាក់ស្រស់។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'women',
      createdAt: '2026-02-21T20:48:39.314762',
      description: 'ក្រណាត់: Silk Blend, ទំហំ: XS-L, ពណ៌: ក្រហម/ខ្មៅ/ស, សម្រាប់ស្រ្តី។',
      id: 8,
      image: ['/images/fashion/clothing/women/12.png'],
      name: 'អាវ Blouse Silk ស្រ្តី',
      price: 60,
      specs: 'ក្រណាត់: Silk Blend, ទំហំ: XS-L, ពណ៌: ក្រហម/ខ្មៅ/ស, សម្រាប់ស្រ្តី។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'men',
      createdAt: '2026-02-21T20:49:10.568018',
      description: 'សម្ភារៈ: Canvas, ទំហំ: 36-44, ពណ៌: សស/ខ្មៅ/ក្រហម, បែបកីឡា។',
      id: 9,
      image: ['/images/fashion/shoes/8.png'],
      name: 'ស្បែកជើង Sneaker Canvas',
      price: 20,
      specs: 'សម្ភារៈ: Canvas, ទំហំ: 36-44, ពណ៌: សស/ខ្មៅ/ក្រហម, បែបកីឡា។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'men',
      createdAt: '2026-02-21T20:49:43.044812',
      description: 'សម្ភារៈ: Mesh + Rubber, ទំហំ: 37-45, បច្ចេកវិទ្យា: Air Cushion, ស្រាល។',
      id: 10,
      image: ['/images/fashion/shoes/7.png'],
      name: 'ស្បែកជើងរត់ Air Cushion',
      price: 33,
      specs: 'សម្ភារៈ: Mesh + Rubber, ទំហំ: 37-45, បច្ចេកវិទ្យា: Air Cushion, ស្រាល។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'men',
      createdAt: '2026-02-21T20:50:05.739435',
      description: 'Smart Watch, អេក្រង់: 1.4" AMOLED, GPS, Heart Rate, អាងទឹក: IP68។',
      id: 11,
      image: ['/images/fashion/watches/men/5.png', '/images/fashion/watches/men/6.png'],
      name: 'នាឡិកា Smart Watch GPS',
      price: 70,
      specs: 'Smart Watch, អេក្រង់: 1.4" AMOLED, GPS, Heart Rate, អាងទឹក: IP68។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'women',
      createdAt: '2026-02-21T20:50:55.792335',
      description: 'នាឡិកា Quartz, ខ្សែ: Leather ពិតប្រាកដ, ពណ៌: ត្នោត/ខ្មៅ, សម្រាប់ស្រ្តី។',
      id: 12,
      image: ['/images/fashion/watches/women/1.png'],
      name: 'នាឡិកា Quartz ខ្សែ Leather ស្រ្តី',
      price: 20,
      specs: 'នាឡិកា Quartz, ខ្សែ: Leather ពិតប្រាកដ, ពណ៌: ត្នោត/ខ្មៅ, សម្រាប់ស្រ្តី។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'women',
      createdAt: '2026-02-22T09:15:22.123456',
      description: 'នាឡិកាពណ៌មាសប្រណិត ជាមួយតួដែកអ៊ីណុក និងគ្រាប់ពេជ្រតូចៗនៅខាងក្នុង។',
      id: 13,
      image: ['/images/fashion/watches/women/2.png'],
      name: 'នាឡិកាដៃមាសប្រណិត',
      price: 45,
      specs: 'Stainless Steel, ពណ៌: មាស, ប្រភេទ: Analog, ធន់នឹងទឹក 3ATM។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'women',
      createdAt: '2026-02-22T10:30:45.000000',
      description: 'នាឡិកាដៃខ្សែក្រណាត់ទាន់សម័យ ងាយស្រួលពាក់ និងសាកសមសម្រាប់យុវវ័យ។',
      id: 14,
      image: ['/images/fashion/watches/women/3.png'],
      name: 'នាឡិកាដៃខ្សែក្រណាត់ Casual',
      price: 15,
      specs: 'ខ្សែក្រណាត់, ពណ៌: ចម្រុះ, ម៉ាស៊ីន: Quartz, ទម្ងន់ស្រាល។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'women',
      createdAt: '2026-02-23T11:20:10.555222',
      description: 'នាឡិកាដៃ Rose Gold ស៊េរីថ្មី សាកសមបំផុតសម្រាប់កម្មវិធីជប់លៀងផ្សេងៗ។',
      id: 15,
      image: ['/images/fashion/watches/women/4.png'],
      name: 'នាឡិកា Rose Gold សុភាពនារី',
      price: 35,
      specs: 'នាឡិកា Analog, ពណ៌: Rose Gold, ខ្សែ: ដែកស្រាល, ម៉ូដទាន់សម័យ។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'women',
      createdAt: '2026-02-24T08:45:00.111000',
      description: 'នាឡិកាដៃកីឡាឌីជីថល ធន់នឹងការប៉ះទង្គិច និងងាយស្រួលមើលម៉ោងពេលយប់។',
      id: 16,
      image: ['/images/fashion/watches/women/5.png'],
      name: 'នាឡិកាឌីជីថលបែបកីឡា',
      price: 25,
      specs: 'ប្រភេទ: Digital, ខ្សែ: Silicone, មុខងារ: ម៉ោងរោទ៍ និងកាលបរិច្ឆេទ។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'women',
      createdAt: '2026-02-25T14:10:30.999888',
      description: 'នាឡិកាដៃ Classic ខ្សែស្បែកពណ៌ស ផ្តល់នូវភាពថ្លៃថ្នូរ និងភាពទន់ភ្លន់។',
      id: 17,
      image: ['/images/fashion/watches/women/6.png'],
      name: 'នាឡិកាដៃ Classic ពណ៌ស',
      price: 22,
      specs: 'ខ្សែ: ស្បែកស, ពណ៌តួ: ប្រាក់, ម៉ាស៊ីន: Quartz ជប៉ុន។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'women',
      createdAt: '2026-02-26T16:20:15.333444',
      description: 'នាឡិកាដៃម៉ូដខ្សែចងដៃ (Bracelet Watch) លម្អដោយត្បូងភ្លឺចែងចាំង។',
      id: 18,
      image: ['/images/fashion/watches/women/7.png'],
      name: 'នាឡិកាខ្សែដៃត្បូង',
      price: 55,
      specs: 'រចនាប័ទ្ម: គ្រឿងអលង្ការ, ពណ៌: ប្រាក់, សម្រាប់នារីសម័យថ្មី។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'women',
      createdAt: '2026-02-27T09:05:40.666777',
      description: 'នាឡិកាដៃទំនើបបង្រួមតូច ងាយស្រួលសម្រាប់អ្នកដែលមានកដៃតូច។',
      id: 19,
      image: ['/images/fashion/watches/women/8.png'],
      name: 'នាឡិកាដៃ Slim Edition',
      price: 30,
      specs: 'ទម្រង់: តូចស្តើង, ខ្សែ: Stainless Steel, ពណ៌: ខ្មៅលាយមាស។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'men',
      createdAt: '2026-02-21T20:51:37.98597',
      description: 'ក្រណាត់: Cotton Blend, ទំហំ: S-XXL, ពណ៌: ប្រផ្នូល/ខ្មៅ, ស្រួលពាក់ប្រចាំថ្ងៃ។',
      id: 13,
      image: ['/images/fashion/clothing/men/8.png'],
      name: 'អាវ Polo ប្រុស',
      price: 50,
      specs: 'ក្រណាត់: Cotton Blend, ទំហំ: S-XXL, ពណ៌: ប្រផ្នូល/ខ្មៅ, ស្រួលពាក់ប្រចាំថ្ងៃ។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'men',
      createdAt: '2026-02-21T20:52:17.782357',
      description: 'សម្ភារៈ: Genuine Leather, ទំហំ: 38-45, ស្តាយ: Oxford, ពណ៌: ខ្មៅ/ត្នោត។',
      id: 14,
      image: ['/images/fashion/shoes/6.png'],
      name: 'ស្បែកជើង Oxford Leather',
      price: 60,
      specs: 'សម្ភារៈ: Genuine Leather, ទំហំ: 38-45, ស្តាយ: Oxford, ពណ៌: ខ្មៅ/ត្នោត។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'women',
      createdAt: '2026-02-21T20:52:55.174403',
      description: 'ក្រណាត់: Khmer Silk, ទំហំ: XS-XL, ពណ៌: ផ្លែបន្លែ, ស្លៀកពាក់ជាប្រពៃណី។',
      id: 15,
      image: ['/images/fashion/clothing/women/11.png'],
      name: 'សំពត់សូត្រខ្មែរ',
      price: 25,
      specs: 'ក្រណាត់: Khmer Silk, ទំហំ: XS-XL, ពណ៌: ផ្លែបន្លែ, ស្លៀកពាក់ជាប្រពៃណី។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'women',
      createdAt: '2026-02-21T20:53:24.935514',
      description: 'សម្ភារៈ: EVA Foam, ទំហំ: 36-44, ស្រាល: 200g, ស្រួលពាក់នៅផ្ទះ។',
      id: 16,
      image: ['/images/fashion/shoes/5.png'],
      name: 'ស្បែកជើង Sandal EVA',
      price: 56,
      specs: 'សម្ភារៈ: EVA Foam, ទំហំ: 36-44, ស្រាល: 200g, ស្រួលពាក់នៅផ្ទះ។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'women',
      createdAt: '2026-02-21T20:54:04.284765',
      description: 'ក្រណាត់: Chiffon, ទំហំ: XS-XL, ពណ៌: ផ្កា/ស, ស្រួល ស្រស់ ត្រជាក់។',
      id: 17,
      image: ['/images/fashion/clothing/women/10.png'],
      name: 'រ៉ូប Chiffon ស្រ្តី',
      price: 45,
      specs: 'ក្រណាត់: Chiffon, ទំហំ: XS-XL, ពណ៌: ផ្កា/ស, ស្រួល ស្រស់ ត្រជាក់។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'men',
      createdAt: '2026-02-21T20:55:01.42339',
      description: 'ក្រណាត់: Fleece, ទំហំ: S-XXL, ពណ៌: ប្រផ្នូល/ខ្ចី/ខ្មៅ, ក្តៅស្រួល។',
      id: 18,
      image: ['/images/fashion/clothing/men/5.png'],
      name: 'អាវ Jacket Fleece',
      price: 67,
      specs: 'ក្រណាត់: Fleece, ទំហំ: S-XXL, ពណ៌: ប្រផ្នូល/ខ្ចី/ខ្មៅ, ក្តៅស្រួល។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'men',
      createdAt: '2026-02-21T20:55:24.694346',
      description: 'នាឡិកា Mechanical, គ្មានថ្ម, ក្រឡុក: Alloy, ស្តាយ: Vintage, សម្រាប់ប្រុស។',
      id: 19,
      image: ['/images/fashion/watches/men/2.png'],
      name: 'នាឡិកា Mechanical Vintage',
      price: 56,
      specs: 'នាឡិកា Mechanical, គ្មានថ្ម, ក្រឡុក: Alloy, ស្តាយ: Vintage, សម្រាប់ប្រុស។',
    },
    {
      category: 'នាឡិកា',
      subcategory: 'men',
      createdAt: '2026-02-21T20:56:26.639932',
      description: 'នាឡិកា Sport, អេក្រង់: Digital LCD, Stopwatch, Alarm, អាងទឹក: 100m។',
      id: 20,
      image: ['images/fashion/watches/men/1.png', 'images/fashion/watches/men/3.png'],
      name: 'នាឡិកា Sport Digital',
      price: 44,
      specs: 'នាឡិកា Sport, អេក្រង់: Digital LCD, Stopwatch, Alarm, អាងទឹក: 100m។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'women',
      createdAt: '2026-02-21T20:56:53.609256',
      description: 'សម្ភារៈ: PU Leather, ទំហំ: 35-41, កែងជើង: 7cm, ស្តាយ: Heel ស្រ្តី។',
      id: 21,
      image: ['/images/fashion/shoes/4.png'],
      name: 'ស្បែកជើង Heel ស្រ្តី',
      price: 66,
      specs: 'សម្ភារៈ: PU Leather, ទំហំ: 35-41, កែងជើង: 7cm, ស្តាយ: Heel ស្រ្តី។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'men',
      createdAt: '2026-02-21T20:57:56.11956',
      description: 'ក្រណាត់: Jersey Cotton, ទំហំ: S-XXL, បោះពុម្ព: លេខ/ឈ្មោះ, កីឡាបាល់ទាត់។',
      id: 22,
      image: ['/images/fashion/clothing/men/4.png'],
      name: 'អាវ Jersey កីឡាបាល់ទាត់',
      price: 69,
      specs: 'ក្រណាត់: Jersey Cotton, ទំហំ: S-XXL, បោះពុម្ព: លេខ/ឈ្មោះ, កីឡាបាល់ទាត់។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'men',
      createdAt: '2026-02-21T20:58:47.20365',
      description: 'ក្រណាត់: Wool Blend, ទំហំ: S-XL, ពណ៌: ប្រផ្នូល/ខ្មៅ, ក្តៅ និងទំនើប។',
      id: 23,
      image: ['/images/fashion/clothing/men/3.png'],
      name: 'អាវ Coat Wool រដូវរងា',
      price: 77,
      specs: 'ក្រណាត់: Wool Blend, ទំហំ: S-XL, ពណ៌: ប្រផ្នូល/ខ្មៅ, ក្តៅ និងទំនើប។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'women',
      createdAt: '2026-02-21T20:59:49.20163',
      description: 'សម្ភារៈ: Rubber នឹងទឹក, ទំហំ: 36-45, ពណ៌: លឿង/ខ្មៅ, ប្រើប្រាស់ក្នុងភ្លៀង។',
      id: 24,
      image: ['/images/fashion/shoes/10.png'],
      name: 'ស្បែកជើង Rain Boot',
      price: 56,
      specs: 'សម្ភារៈ: Rubber នឹងទឹក, ទំហំ: 36-45, ពណ៌: លឿង/ខ្មៅ, ប្រើប្រាស់ក្នុងភ្លៀង។',
    },
    {
      category: 'សម្លៀកបំពាក់',
      subcategory: 'men',
      createdAt: '2026-02-21T21:02:11.509639',
      description: 'ក្រណាត់: Oxford Cotton, ទំហំ: S-XXL, ពណ៌: សស/ខៀវ/ប្រផ្នូល, ស្លៀកទៅការិយាល័យ។',
      id: 25,
      image: ['/images/fashion/clothing/men/1.png'],
      name: 'អាវ Formal សម្រាប់ការងារ',
      price: 67,
      specs: 'ក្រណាត់: Oxford Cotton, ទំហំ: S-XXL, ពណ៌: សស/ខៀវ/ប្រផ្នូល, ស្លៀកទៅការិយាល័យ។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'men',
      createdAt: '2026-02-21T21:02:42.064615',
      description: 'សម្ភារៈ: Suede Leather, ទំហំ: 37-44, ស្តាយ: Chelsea Boot, ពណ៌: ត្នោត/ខ្មៅ។',
      id: 26,
      image: ['/images/fashion/shoes/2.png'],
      name: 'ស្បែកជើង Chelsea Boot',
      price: 67,
      specs: 'សម្ភារៈ: Suede Leather, ទំហំ: 37-44, ស្តាយ: Chelsea Boot, ពណ៌: ត្នោត/ខ្មៅ។',
    },
    {
      category: 'ស្បែកជើង',
      subcategory: 'women',
      createdAt: '2026-02-21T21:04:40.042704',
      description: 'សម្ភារៈ: Knit Fabric, ទំហំ: 36-44, ស្រាល: 150g, ស្រួលពាក់ក្នុងផ្ទះ/ក្រៅ។',
      id: 27,
      image: ['/images/fashion/shoes/1.png'],
      name: 'ស្បែកជើង Slip-On Knit',
      price: 23,
      specs: 'សម្ភារៈ: Knit Fabric, ទំហំ: 36-44, ស្រាល: 150g, ស្រួលពាក់ក្នុងផ្ទះ/ក្រៅ។',
    },
  ]);

  constructor(private http: HttpClient) {}

  get productslist() {
    return this.products.asReadonly();
  }
}
